### ISSUE TITLE
Historias de usuario

### ISSUE THREAD

**Issue by magaligarcia** [magaligarcia/ProyectoIntegrador_FullStack#5]
Acá dejaremos una lista de las historias de usuario que luego pasaran al backlog por separado con sus respectivas tareas.

**Comment by magaligarcia** [comment]
#US01: Como usuario quiero crear una cuenta e ingresar en ella para adquirir productos y/o servicios

**Comment by silviconi** [comment]
#US02: Como usuario quiero que el sitio me permita reservar con anticipacion una mesa para degustacion de las distintas cepas.

**Comment by silviconi** [comment]
#US03: Como usuario quiero aprender mas sobre las distintas cepas para su futura adquisición.

**Comment by vlysi** [comment]
#US04: Como usuario quiero agregar productos al carrito de compras

**Comment by yanetabares27** [comment]
#US05: Como usuario quiero reservar lugar para almorzar o cenar en la bodega.

**Comment by vlysi** [comment]
#US06: Como usuario quiero reservar un turno para realizar visitas guiadas.

**Comment by magaligarcia** [comment]
#US07: Como usuario quiero acceder a información sobre la bodega y sus creadores para conocer mejor su historia.

**Comment by magaligarcia** [comment]
#US08: Como usuario quiero reservar un turno para dar una cabalgata por el viñedo.
